sudo: required
services:
  - docker

before_install:
  - docker build -t dt5513/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dt5513/react-test npm test

after_success:
  - docker build -t dt5513/multi-client ./client
  - docker build -t dt5513/multi-nginx ./nginx
  - docker build -t d5513/multi-server ./server
  - docker build -t dt5513/multi-worker ./worker
  # Take those images and push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dt5513/multi-client
  - docker push dt5513/multi-nginx
  - docker push d5513/multi-server
  - docker push dt5513/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-020225586511
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
